#!/bin/bash
which df 2>&1 > /dev/zero
if [ $? -gt 0 ]
then
    echo "no df command"
    exit 1
fi

which awk 2>&1 > /dev/zero
if [ $? -gt 0 ]
then
    echo "no awk command"
    exit 1
fi

df -h | awk -F '[ %]+' 'BEGIN{c=0;s=0};$(NF-1)~/[0-9]/{
    if(NF==1) {
        name=$NF;
        c=1
    }
    else if (NF>1 && $(NF-1)>99 && c==0) {
        print "I am full~~!!",$1,$NF,$(NF-1)"%";
	s=1
        exit 1
    }
    else if(NF>1 && $(NF-1)>99 && c==1) {
        print "I am full~~!!",$1,name,$NF,$(NF-1)"%";
	s=1
        exit 1
    }
} END{
    if(s!=1) {
	print "No news..."
    }
}'
